buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:[6.0,6.2)'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'java-library'
apply plugin: 'idea'

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'

    exclude '**/*.bbmodel'
    exclude 'src/generated/**/.cache'
}

repositories {
    maven {
        name = 'GeckoLib'
        url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroup 'software.bernie.geckolib'
        }
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }
    maven {
        name = 'Architectury'
        url = 'https://maven.architectury.dev/'
        content {
            includeGroup 'dev.architectury'
        }
    }
    maven {
        name = 'ModMaven'
        url = 'https://modmaven.dev/'
        content {
            includeGroup 'com.github.glitchfiend'
        }
    }
    maven {
        name = 'MoreHitboxes'
        url = 'https://dl.cloudsmith.io/public/darkpred-mods/more-hitboxes/maven/'
        content {
            includeGroup 'com.github.darkpred.morehitboxes'
        }
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', file('build/createSrgToMcp/output.srg').absolutePath

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            args '--mod', mod_id, '--all', '--output',
                    file('src/generated/resources/').absolutePath, '--existing',
                    file('src/main/resources/').absolutePath
        }
    }
}

tasks.matching { it.name == 'runGameTestServer' }.configureEach {
    doFirst {
        project.copy {
            from('src/main/resources/gameteststructures')
            into('run/gameteststructures')
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    implementation fg.deobf("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    implementation fg.deobf("maven.modrinth:fossils-and-archeology-revival:${fossils_version}")
    implementation fg.deobf("com.github.darkpred.morehitboxes:morehitboxes-forge-${minecraft_version}:${morehitboxes_version}")

    runtimeOnly fg.deobf('dev.architectury:architectury-forge:9.2.14')
    runtimeOnly fg.deobf('com.github.glitchfiend:TerraBlender-forge:1.20.1-3.0.1.10')

    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}

def generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    def replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            geckolib_version       : geckolib_version,
            fossils_mod_version    : fossils_mod_version,
            morehitboxes_version   : morehitboxes_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar', Jar).configure {
    finalizedBy 'reobfJar'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
