org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Runtime
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.3
forge_version_range=[47.4.3,)
loader_version_range=[47,)
geckolib_version=4.7.2
fossils_version=1.20.1-9.3.4.0-forge
fossils_mod_version=9.3.4.0
morehitboxes_version=1.9.2

# Testes
junit_version=5.11.4

mod_id=iceagesurvival
mod_name=Ice Age Survival
mod_license=All Rights Reserved
mod_version=0.10.0
mod_group_id=dev.madebyfelipe.iceagesurvival
