'use strict';
const token = document.querySelector('meta[name="coordination-token"]').content;
const board = document.getElementById('board'), sessions = document.getElementById('sessions'), status = document.getElementById('status');
const stages = {entrada:'Entrada',pesquisa:'Pesquisa',decisao:'Sua decisão',pronto:'Pronto',executando:'Em execução',bloqueado:'Bloqueado',revisao:'Revisão',concluido:'Concluído'};
let lastTasks='', lastSessions='', updating=false;
const drafts=new Map(), expansions=new Map();
function rememberDetails(details,key){details.open=expansions.get(key)||false;details.addEventListener('toggle',()=>expansions.set(key,details.open));}
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json','X-Coordinator-Token':token},body:JSON.stringify(data)}:{});const result=await r.json();if(!r.ok)throw new Error(result.error||'Operação recusada');return result;}
function button(text,action){const b=element('button',text);b.type='button';b.addEventListener('click',async()=>{b.disabled=true;try{await action();await update(true);}catch(e){status.textContent=e.message;}finally{b.disabled=false;}});return b;}
function decisionForm(card,task,path,label){const form=element('details');form.append(element('summary',label));const note=element('textarea');note.rows=3;note.dataset.focusKey=task.id+path;note.value=drafts.get(task.id+path)||'';note.addEventListener('input',()=>drafts.set(task.id+path,note.value));rememberDetails(form,task.id+path);note.setAttribute('aria-label','Decisão ou evidência registrada pelo Felipe');note.placeholder='Registre a decisão, evidência ou motivo';form.append(note,button('Registrar e continuar',async()=>{if(!note.value.trim())throw new Error('Registre uma nota antes de continuar.');await api(path,{task_id:task.id,note:note.value});drafts.delete(task.id+path);status.textContent='Registro salvo · '+task.id;}));card.append(form);}
function renderTasks(tasks){const focus=document.activeElement;const focusKey=focus?.dataset.focusKey;const start=focus?.selectionStart,end=focus?.selectionEnd;board.replaceChildren();for(const [key,label] of Object.entries(stages)){const column=element('section',undefined,'column');const items=tasks.filter(t=>t.status===key&&!t.archived);column.append(element('h2',label+' · '+items.length));if(!items.length)column.append(element('p','Nenhuma tarefa.','muted'));for(const task of items){const card=element('article',undefined,'card');card.append(element('div',task.id+' · '+({read:'Leitura',write:'Escrita',manual:'Felipe'}[task.mode]||task.mode),'muted'),element('h3',task.title));if(task.lease)card.append(element('p',task.lease.executor+' · '+task.lease.owner+'\nBranch: '+task.lease.branch,'muted'));const details=element('details');rememberDetails(details,task.id+':packet');details.append(element('summary','Ver pacote'),element('p',task.context),element('p','Conclusão: '+task.acceptance));for(const ref of task.refs||[])details.append(element('div',ref,'muted'));for(const decision of task.decisions||[]){const note=decision.details.note||decision.details.reason;if(note)details.append(element('p','Registro ('+decision.actor+'): '+note));}if(task.summary)details.append(element('p','Handoff: '+task.summary));if(task.evidence)details.append(element('p','Evidência: '+task.evidence));card.append(details);if(key==='pronto'&&task.mode!=='manual'){const actions=element('div',undefined,'row');actions.append(button('Claude trabalho',async()=>{await api('/api/launch',{task_id:task.id,executor:'claude-work'});status.textContent='Sessão aberta · '+task.id;}),button('Codex',async()=>{await api('/api/launch',{task_id:task.id,executor:'codex'});status.textContent='Sessão aberta · '+task.id;}));card.append(actions);}if(key==='decisao'||(key==='revisao'&&task.mode==='manual'))decisionForm(card,task,'/api/approve',key==='decisao'?'Registrar decisão do Felipe':'Registrar aprovação do Felipe');if(['entrada','pesquisa','bloqueado'].includes(key))decisionForm(card,task,'/api/ready','Autorizar pacote definido');if(task.lease)decisionForm(card,task,'/api/reclaim','Recuperar reserva (após parar a sessão)');column.append(card);}board.append(column);}if(focusKey){const next=[...board.querySelectorAll('[data-focus-key]')].find(e=>e.dataset.focusKey===focusKey);if(next){next.focus();if(start!==null&&start!==undefined)next.setSelectionRange(start,end);}}}
function renderSessions(items){const ids=items.map(s=>s.id).join(',');if(ids!==lastSessions){sessions.replaceChildren();for(const s of items){const section=element('section',undefined,'card session');section.dataset.session=s.id;section.append(element('h3',s.task_id+' · '+s.executor));const state=element('p',undefined,'muted');state.dataset.state='';const terminal=element('details');terminal.append(element('summary','Ver terminal'));const output=element('pre');output.dataset.output='';output.setAttribute('aria-label','Saída da sessão '+s.task_id);const input=element('textarea');input.rows=2;input.setAttribute('aria-label','Mensagem ou resposta para a sessão '+s.task_id);input.placeholder='Responder à sessão';const row=element('div',undefined,'row');row.append(button('Enviar',async()=>{await api('/api/input',{session_id:s.id,text:input.value});input.value='';}),button('Parar sessão',async()=>{await api('/api/stop',{session_id:s.id});status.textContent='Parada solicitada · '+s.task_id;}));terminal.append(output,input,row);section.append(state,terminal);sessions.append(section);}lastSessions=ids;}if(!items.length){sessions.textContent='Nenhuma sessão iniciada por este painel.';}for(const s of items){const section=[...sessions.children].find(e=>e.dataset.session===s.id);if(!section)continue;const output=section.querySelector('[data-output]');if(output.textContent!==s.output){output.textContent=s.output;output.scrollTop=output.scrollHeight;}section.querySelector('[data-state]').textContent=s.exit_reason==='handoff'?'Pacote entregue':s.exit_code===null?'Processo ativo':'Processo encerrado · código '+s.exit_code;for(const b of section.querySelectorAll('button'))b.disabled=s.exit_code!==null;}}
async function update(force=false){if(updating)return;updating=true;try{const data=await api('/api/board');const encoded=JSON.stringify(data.tasks.map(t=>{const copy={...t};delete copy.updated_at;copy.lease=t.lease?{owner:t.lease.owner,executor:t.lease.executor,branch:t.lease.branch,acquired_at:t.lease.acquired_at}:null;return copy;}));if(encoded!==lastTasks||force){renderTasks(data.tasks);lastTasks=encoded;}renderSessions(data.sessions||[]);if(status.textContent==='Carregando estado local…')status.textContent='Estado local carregado.';}catch(e){status.textContent='Não foi possível ler o estado: '+e.message;}finally{updating=false;}}
document.getElementById('refresh').addEventListener('click',()=>update(true));
document.getElementById('new-task').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,b=form.querySelector('button');b.disabled=true;try{const values=Object.fromEntries(new FormData(form));const task=await api('/api/task',values);form.reset();status.textContent='Pedido registrado · '+task.id;await update(true);}catch(e){status.textContent=e.message;}finally{b.disabled=false;}});
update();setInterval(()=>update(),3000);
